apiVersion: v1
kind: Service
metadata:
  name: fastapi-chatgpt-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-chatgpt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
