apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-preparation-deployment
  labels:
    app: offer-preparation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-preparation
  template:
    metadata:
      labels:
        app: offer-preparation
    spec:
      containers:
        - name: offer-preparation
          image: offer-preparation:0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://offer-preparation-mysql:3306/offer-preparation_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: offer-preparation-mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: offer-preparation-mysql-secret
                  key: mysql-password
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
