apiVersion: v1
kind: Service
metadata:
  name: offer-preparation-service
spec:
  type: NodePort
  selector:
    app: offer-preparation
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      # nodePort: 30080  # opcjonalnie: je≈õli chcesz konkretny port
