spring:
  kafka:
    bootstrap-servers: my-kafka-kafka-bootstrap.kafka.svc:9092
    consumer:
      group-id: offer-prep-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
chatgpt:
  base-url: http://fastapi-chatgpt-service:80
  timeout: 5s